---
- hosts: homelab
  become: true

  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Add USB storage mount to fstab.
      lineinfile:
        path: '/etc/fstab'
        line: "LABEL=terabyte  /media/terabyte ext4    defaults        0       0"
