---
- hosts: homelab
  become: true

  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Add USB storage mount to fstab.
      lineinfile:
        path: '/etc/fstab'
        line: "LABEL=terabyte  /media/terabyte ext4    defaults        0       0"

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Internet Monitoring.
      ansible.builtin.import_tasks: tasks/internet-monitoring.yml
      when: monitoring_enable

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Set up Plex.
      ansible.builtin.import_tasks: tasks/plex.yml
      when: plex_enable

    - name: Set up Arr Suite.
      ansible.builtin.import_tasks: tasks/arr.yml
      when: arr_enable

    - name: Set up tailscale.
      ansible.builtin.import_tasks: tasks/tailscale.yml
   #   when: tailscale_enable

    - name: Set up AWS cli.
      ansible.builtin.import_tasks: tasks/aws-cli.yml
      when: aws_cli_enable

    - name: Configure samba.
      ansible.builtin.import_tasks: tasks/samba.yml
