---
- name: Create Plex folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/plex"
    state: directory
    mode: 0755
  become: false

- name: Copy plex docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/plex-docker-compose.yml.j2
    dest: "{{ config_dir }}/plex/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart plex

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Plex is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/plex/"
    build: false
  become: false
